{
	"data": "ENC[AES256_GCM,data:q8xO6JvBn01J0grcB/3nVkaFqyJQDGGUkVHpwFILyd7VH8efy5G8yNP6fqLcE7/4tPaNWqmRMMXPspSKU6Iqa/vRfvC6f8J78mqBaXnPm0lwEBNwrgKdLQURy8tOxiaa1RVZ2vzmcNLQkminkcCg9ZaeiILI0hmz+r36oP7DR1Dl2RrRknDC9pRSWDaldWmF/ARkqZ//J9Emos8xeM4GKtfi9PjDH2JdGwXv4RLfsH07Lg5JQKW/x9ZR1naaiLBngh8954E2/0qrZ4CoS+pa+YEatXXRHdWHycfc6M4J5NWcMVHa2zXUn/4RVM216HV/NWkXzSfX53WNVnq2h3G4PtBDaOO+r/+Nudh8kfshJWghOyS03aXyuEezNSIPov1nJaaHjOrZDqvuC/+pZOnFg5E/E6iXokR2mtVznpQPpDWU/h/rQ+5SixYY1DiZMQaiAoenDfmdXy0i+WmKIDwXmMMcRQAYOusRnjIRxJonkpZu63RLJZyohhBuso3ekHplpIvxBrJdcuC57JaU+AzoxTRe9tOCSR+spA6fIX0wEXdRyXeRaacPGEJkskEL29oy7197E9h3hz6UDW8upmvL3Ns/Bdmgux5Le+UttlYFl1/SHL1NS7t/zZ3P5/ot9Na4jR/LNeZqhqSADpEJo6NaBoqVtSYdrvOeJ1Z24v0PaNahP7TbLJzohOddDy+uTFgHKjP1dGng3KKFCaqz3dmBuydcFnE5xm2X0qjW25upBGLWsrPt24RDnsDUMWtz5CRdjRqZZhjemMK1lsjj0C/knb4r7Th2Kw==,iv:HfKGFBzJpAoVIu5PHn3aTqBry3++Tf7/MYbELx3EVa0=,tag:BlLCJZGUdmfLF0uKIKXF5g==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM1NDcTRoUms2Wkx5anFj\nbVFFOXFZb0NzTFltOWkrK1dqMDVVUDZsY3dnCnZ5bEwyajVsNG9TS3gwWmE3MFJh\nTS9vaGZxaVA1Sm1DUjhVUEN4NDZZZXMKLS0tIExnam1icEFDblN1WitlWVVYUk9U\nSXB2MmdtLzJRQk1wUzZjRUFxcUM2eEkKAkqnqphy8tVGHRWrdHruLoCmd/2cP0O0\nUhUoxG+TfYFDB7oul8VmjClhxeMhA2OxUVDXL34d3bBgadRGmfD/xQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-12T09:08:31Z",
		"mac": "ENC[AES256_GCM,data:TAXeQhoDeUGNdzKIulAuD6/rvDG39+FsPV9UlC9ldnyHYNj1Qu4TS4iOpC/vO0CUCKi/IKaYMP+1w+/KW5zzKvBqVso6aHuhFp/6px16nvtnOWZjhZgt1+NTnXsP2wvmdhmVO417HYacaTeiKJQlpMZl6rcPQZqCBoymweGF9y4=,iv:bOX5GirIaWEDNdLiNhl0c1CpXSyZqMXaDQdl01/1HSk=,tag:52Nl7/mz3wpxPK5ryah0Eg==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
