{
	"data": "ENC[AES256_GCM,data:FGVHZjJ7PYJZvg6zeSD1hDBk/BHjTRnpd0RE6RdfUgRLMatd9F7svaxj4FtG872PyTqftEZgbMGWFn8M8mGORV88SQszHunU8nItlKG3YhtBJigIalnYth+L+oZzjnt3FxRw8pVq28LBU+UZ/rIcjQ1CrZZsSHYgXtwwA/2GhdZPb0KDiUKHct/nR4K4czXLhWAQ1f+xfi0WRbnm+39fcDNTR8YPUG3s3ndC7xCWqSLlYsM5ZC7IxuHGE+K/NJDVj9f1CICdFG7Wcv8WSI2uOjG8lmRcQuT95u940glUnq7d5NinQ0OzPYpPQiLJN5sI7KQal9zYAVFC7D8bVdG12imWr+66TJ9+j+TN7Wu0qpb1zn1FUcbY3WtSdXKCJvGUKCskQmaK8yUgQswkFkJQ3MBXa7+r/88Re39exP3PyxFRqHXOFopXhwAhfLlJeKk4x+ExjWeAuQe/NV++7g1V8eveZc321tdSSX9uqbUnMay5NKC5ezxPVxw4SXaKTZIiVXuaskTiI4ve8O6WIZVtk4RE5yzT+vxHbUpSiNHo0q8XcLulwjGSwkUsH4uai+kmGehYfkfFcSJZHJ/6kLnw3fZSY61YC1bpHR7YtN4sJ3uhNp4PXpEwdcMGetdZr+iVSS6RmDrJGGIAS8tPRt8gKjOapYR3acGaeQImCiLi440SzHN9NHHce9qtJFRFVg9DkVUoG1zP5N4hbQbK0hEE7YNCunemJybQ7ZGsXpaArA6xJVvDssO49o/H/5+dJQ/o+rbY0VgB4779aycEhxb0OkE+eoPbvQ==,iv:L03xU4yfHktCMk5OwQcuDYua/J3DlbnwR+b8O1ZZVLw=,tag:VMw4injfDBiQE+pN1KtElg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd2xQZnlpV2lLSkhYeE0z\nMGxWRm44YTBMcFk5UmJRZkVLcFhrZ29DZUdjClpNM05jRmVGMWdlN0U3ZFBtVzhH\nL3k2OFdjci9qZm5ReHhjYTdTbXAvMncKLS0tIFFFZkg2OEdmS2xRYTB1aE02QUtW\nSnRWbDdxU3pEdW5MYUNHQXE4TmdZa3cKFP502Y/VZX0yopTFoTt8c9uvkA04ZlAY\nEd8TvLYfMx1OIvZRZER6q0WiIAZd7Qs1LvcTRsWDLvgE77myzx4vwg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-20T09:29:39Z",
		"mac": "ENC[AES256_GCM,data:+t2LNGZNUAA3TzNGtJzFN2ghxWeH5QvbQzvu9ymkHwRbPXVq9ovO2gWhYyPDrwBwzuyUzo2ZK5wiF0KsWJIGcewoSYxnsEk3E/m7vyyP6cATd9eaeXu1rJrLfC4akNUIqRNdKHDiAKXQf6dVRHTwyXKt03jJIimIorNbSH8w0uo=,iv:eBSwJjfSuQIdU37fEMhPTvHdiwfFMdg6vF0rpm+GtHc=,tag:7z7jPkBa9vCIlNcCVz+OLA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
