{
	"data": "ENC[AES256_GCM,data:E6fpHazByMPLGu28dwNmOcwRwkIyqKoaSvImeDf2HDBOsK9xbFBABEaBX1YOswRM6mN56dgljtBGGXiRO3Hcc9nZcb3EGGA4EFS3zFrnj/yUTCoDPZofxgxzGs2jnxt0oKgYJt6VXG10Vc1bzOGW2V6u+KeVl87EmajXjNSk5KyLIV+MP3mqi8hVDaO1LVAFlaO4pnHEEoLvq+2jarjVIwtPHrUFZHop5YSGri57QScC/rVDUHTmS4qMkdHEZDZQ76eX8bwdUHbEsQUiMgn+Kam+8z+8Z6xHxu3zXs3TD0tucRjNTFuhK6ctqYX2JpY/qFST7ZFMa575XNxJEeXg4eegrfsHXi2g7Rq9gQf5xzlraceZ1uJja02CkLS4KVJwF5/fexhs78wLL8ZSIVkG7QNCGbM8aPF9Psi31b/IsLmMY5i/WLM8L74S8WTDILK7bqdYjjAdPSyNni6s7swECZW6Sc73K0MajIfLhGoJpBO6YLRT6ksliXKGq9u2olK4OrawSLMCGlzZ0IO7Pa+PH2P1SxjQDo0sbTkXwVU6S4r7LuPofG3AO34ytNy1fRLe7X9+X6V3VO4NaHR5DYG2rbTDXFLbqUvWg1fdLJMZkHd7ZbTZ/+ii2E9KJAIQPMtyjjDZcScrtlQ6XyVQ9Sm0jXEX4KEbBg50S/KcngvkXcIc5i1rmmzF7/gjno8PFABagCQJGf230Ky+C0VVGjkFGNNTSuE95bdyAQ8l1i3tDAqyzwDghlMI3poXWfxTIwlVm7itSwlhx/z0crNDDnQTPw==,iv:ygLK5gqsxDN2vGOWORTjb6uIjCXtxsEQ9G3l7iOvbYc=,tag:h5uxWiFye8JP/GkeurJ+jw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueXBjOGNWUDNtdHlEcFN2\naWkvODdTRGpEQjNPMmhHdytWbC80Tk82cGkwClRHMjdrSWV5bFhEZ3M4S0FzbWZQ\ncmNuOWo1Wk5jN29VUThYaTdTM0xqancKLS0tIGRqb1AzWHpiZ2ltam8wVWFiTUhp\nbkczM1VnWnl6L2dFUk1DcGxzUVlkNEUKC1fg6FeXKqrEVkHjz2USOog30SrAxYi6\nMmQT7iP/mcx5SBoCwT8rTGiQoJG11HuYTYrGuTOLGcHRjylV8Hhv7A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-06-29T00:37:17Z",
		"mac": "ENC[AES256_GCM,data:QCVmwdl/tYVS0Go1PEyYwYWtaUNM8RegAK3Zr5KMh4fPaQkpFJlk8Y/zBmLOhKKjz+54Q5p2Uf6HtOASQnzGRhYeFb7GlDOUTESJiPqfrpl1Uw9FyVDOVtOZJKzNaJ+mSYoG0NNzNTd5uOWs/wIQlE4jZ971rtpkg4keOKV9StQ=,iv:cjnLZidjmRrmlGriqgLfvNxYKdixvsmARVSTKc70XmU=,tag:xs8WkNsO+zbszKuNYCSOCw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
