{
	"data": "ENC[AES256_GCM,data:jDohDF/2bYPndLpMrFx30B6PnaveqHqHAKb9rQFqNQi6OpZ1cCvzaK15W+h38/Z3VsVPd5TLOZexqIdIUho4W201U0NBbUQ73THmdhjIgNuW6XqTmw/ulvB4G3GHoAImHfctxvwwj6kg5brSwzWu3MMGHJfmqvD8POnWJdlBt1NOahMaVF0lqCHuyl01T6aB33Pzoa/ZwECOsVdLxjRlzD8ENZupt/4h9pwkNTarsgO1Fd8zSfzkK/Di1u6ZEkBmJne+FkDeR2HgMqs4tMEZ6FkFjlO+V/UnNCxd8uMKP+IsOUdnlf7JnU474UUT9NkbKB2QkpYE7UGU6lbaPX28jwq8DKqH4SaplszaRiwnXVvnLMAZwyOSWZ2TrjSIUNvjcqWZmq2DHnkACrY5kG5XMTLLZmHEQHFlXZ0+74CfEjZh5uV6JqvWXb3fTt/ufLKuSFpUEnpWf95myCfv6V2cQXB0xL23FZb9w6OQIEQkB1RjkIbbiOdwrm3OoldD/7KLT473rIFpBnf8KL9uNXZ5jATZulazNTKuGzdi7aQEFrOLBi4wf7fa68/ObUF8tZcQBfHFUVB4X0saRf3waMkmI7agAM6OVuosAbNdaCaPVemW9eAD73cq7Uq8kDsnkbKsQ3f4AFpKpqeIhiCqNiviWfOxOtf2Rww22hg05SkvffkTUbKaNSatEgzOsp+wKVhIYkEJxnFqHJ79mL2PZNMXb/r6dkCZIzoAvNa0tMZ4wTpOa4ilJDuK0jOYvKzRJyFmwVaFTvPk4n+tBC0Bi7rYIA==,iv:sEpteLhenShGKFEjB5n4VlkGYUsoVktgOFm8LIo5uFg=,tag:Gte3FXkDkNKFXlnWdCJQbg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZDQ5ejJ4andXRWwwVmcz\nRnNKZzhIdk9HYlNzWWVPUldSQ3FDUjc4dFdFClJkRUNXLzl4M2I1Rk9xc0FZRVVl\ndXM3aVdvZjA3WVR6MFMwVk4wMHVFNFEKLS0tIFpZVGtXR05YaFZGZDdRWkNFNml3\nU08zaEc0LzdmeHRYZ1R0S2tCUjJXWTQKcKlzQjnDOCWULYb5lBuYlUVcF6qaW7MS\nMXUnCjMiOMxQEBleVCg5MDsI3+l+2u/cCb8vZYr1xcyTFG+mgbOKaQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-06-29T08:37:16Z",
		"mac": "ENC[AES256_GCM,data:FOCX28HJJdoVH/u8Mjw26q6JjkSUubDT9TAXgncuErtl3PciRhqaYEVTtQLFIjjpxslnjttvw1DJzciqSIDFM0l/bko6Oz1bgLYvwnpev0FjMqQvtOPuvRYxFjFzhleFmVAKPM6cbS/Vs4Hb30vye/3YU4J5IbRz6x187R2plbU=,iv:M0ji5lh2N+YGupJ3doSskx+vOBG1QZB1kv5HGjwVEKg=,tag:KM8GSVHlqEHo87awlvVqKA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
