{
	"data": "ENC[AES256_GCM,data:fDZDSP4U+j+K2mnisLZ9NySdQ3JiGza6sDp9Q6otX+8TLQlRs6fg60+dd4u7K/m9aK8hvz6pZD/ZL/hkf4QmkTCIFoLS3lCPvfbJCgun4nwSg85qEm0CG7N9aHwXu4M624Gr0TzsftF9k9Hz20phw9bxCG+Nn0huU23ikcjrWtJOlNQS4ASgC/2WSNZtr6NqhZY4FXK7nC6eRFPA41iJ6rrlweQTW+di5/2Ncvew56eTRmyrDf6FFcnMrXmYjZz/08PeQGqgOlaaHZDR5bEBYZw6ZHFnx6THiIimN1z0JgVPSczcVT4G7kPDWuWRm5plfVAgtjApu2iC3VPakax0jNMUeR39UWs+yjwesAYgptF2sF3mwqvvj6zxpgQkjvjYhl6yRygpt5VLcgIcO3JQKZEVerDvuHB/TrtaG2mbDnxHcLU8/b7IAOeRjzqhN4yxlw6Bx0q8NBUJxDeMfOnF+M0i5jvgTBfTv4UMhddAj+3wK63zdXeqkDXHxy6vqiJAq6GCJagCZ/ldphOpYdIKoXs4sgvvbUevnTHcer2zyda3UuWcjCZLJiw5sDYdyXzksNltuNZahIxVEZPAeRp8098tOTwUpFHxtX5p3iQLCro/7w4IQS9kR3TkUPxd6BFsOcx62XTm7TIgNjdNetcmJTTG7wtUNMRzm+D8SXVuMk9NVVixT8H42sIbCcHQnJKa7lp9MqB1NwqWdyQHsvlfPeciPjoPXc1nFwktOoca0cSN0PNDJr4eKY2yU5D6rZw8sNaBqBIwXas673OWuA3/z7ozjpVYMg==,iv:HvUOCFrjj/pPFyp49miqpyW1MDLqvPjIHogzk5O/tsQ=,tag:nx6vdYdXPJoF8jNByxwSQQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVFduVy9rTUJsMnlOOXR3\nekhsc010Y3dTUklQL3cvMkNDVTZNYTUwZHhnCjdmMHJBZEFzT0oydUswaGVPQmdz\nZFAwSzdoN0wxM1RlY1pnOXA5REZ3MmcKLS0tIFdhZVZ5clFWT29NaFZLR1NTbkNn\ncHVtbDVSZXUvWTlTOUwyTVBZUkx6SkkKeN3gaTJCmocKrk6hHZb9C7kv05N4RHR9\n306TItkCf0xzBUxJqStKD1Lr6oyd83u9xuOGt8sxGYq5z7SppZt4zg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-04T14:58:56Z",
		"mac": "ENC[AES256_GCM,data:z299B/ITEZowYzSAw0npyZx32HEa8YM5yHMhOlmqwwPiW/bMT4Bb6sblZIrRxsMr2u39JtmO6YiCJMPvxySwXRIIoAjsYpW1jTxRSizgETWc1h1pnTIUhKTPZc4u8F737FwnWOrxqGbODBfUpwXYTvsVrqS+6vE3umoDpNJswyo=,iv:lF6Yg3SNuq5a4yzkXTqVWASUIe4lpT1X4nQfxZzGppo=,tag:ySjPs/ATx/cdAVfTOTCdnQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
