{
	"data": "ENC[AES256_GCM,data:Av6nP9GCXsyCYTzP+gur7mob6l2SJlwoY/d9yb88tVrJ6wyQBztDanijrUCmAwJEF6KsNZlLr/XwK0Bo9+pHoS2JNxX70enqtnF6rJ1fZ+kiK9Bkm9oJBqxWjO0hw6Xdq1qQCrIpODtBevQD9EPFJ7VfTnG5zmUzEBEsSFDIM0ErcMZeSckuSn0WJaTCyI9SlyCpyCTbd1Q+6Fr6zJaIPUCZP5lOtOJhndGsD/3w0srWiMP5crTb10G4TOJu8jZOblB+cRHbpBqVr99Wqp8itVoAwwOIjuc4hGtxcaM+H9V6YTNZfHQUVMRlsxMPJ5qgw/UIrD+fw256mSuO3zExI6ocbhKI7wPXTh2if+006LmCkoScSRGiGQd84gDZbesNbJ+w5u1tqKgRYi45WNsf8EY3SxYrooQSlj4bYvLBw/g0QkFwK1NUE2ZrLzitlQs94SeS+PbCpUycZfVztI2H5y1que9YIQ18BUPUF26fsjzJSR7yhOijtoPQPv+ezxSXM+uscXuce9rFEj2Zo4w5T2Uxu8jW6FIkXUr3adPt1ewYBymcbpUKpGt2YI23viic+TiDHGMLp8lG2GJkJht3QLOYgzUyPZjFmKhHnwUdCXssjOOtyCM6n+ML+p4P1Y33RLZmJi6Qc5E9UF2sDwT/6SUpgty3Z8wvjSqq5akD1JcuKatLLgZ7BYk41l7JlKk3bgnDlnd35rMFSZh9r1w7hAuiUFZvFkOw2qioFAVP2ypzqRce9S/q9z7cSafhH9/1nXGf1M5pbGQejbYcNbppEDhUBWoLWg==,iv:N0nq/47njpZp3CJ02pfwVTvN4sGryo49sVJRkDPH5cc=,tag:r54g3W9+DaXfKSGHI10QTQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcy9XTmVrOGtzOFFncGs4\nck5BQ2tEcHBuMlRQQ3FnSUUzVWVwQktTYVJvCjhmRVNxQmt0V1ZiRzYrSjdvZlU3\nTXNXaEF0MjVCL0lQNVVkYjFVRloyYkkKLS0tIEsra0Z1N1VqS1pZd3F3R1ZQK2pa\najh2bm5uUUR2NThncVdKbExEVUNmTEEKdc/fpL63M/Sc4KAh9DBFl3y4tFnQMjUj\nQfDAkrofXx34DU/zD8r828txBOMUcoDuI4BGRXtTT3gijwYJMCWf0w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-21T01:44:57Z",
		"mac": "ENC[AES256_GCM,data:wkquNJOhp85iAqdLHJioIkPgptRnYc9NPzyV/LidRtMzlVGfwCQJFXVarNtkLlpD6ZAKFNglLjxHOdnH/V4j6+Y5+raDQg90H93U5QAbF8O/3BES18FNR/ZO/AW/Otiv7C6xe+0NerDE187y7Mpb2V5GAimO8bNtkMxEBn+oc1E=,iv:478I3PzU7nfSc5ZVRfraPEyjKruDuK4q3WAd7Fg2IFI=,tag:qBnQIAj5r6f61yS+jYT2Lg==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
