{
	"data": "ENC[AES256_GCM,data:uh9ZsA9/GexSC0XbqllkbyINBZPJKKw3xBe7HFPxK0H4g0+9jS1uMnNRayuG/nrtFweWCLQ4XF8Shr3w2K0se1IKgoXk3A3XVeQxKpl6BBnN5pNeRmjL9GOY9h7GGL/OUOLgZT8YSMtDfgwPIGMjnSB2Nh5tH6Z7aVrCXJsrqxvVQ5RLpzICn23GSDHp/ArjJu+3g8SOV5vGwhMna7MBhH/MmaIUz3B5dmBlTGwcrMeJfBc0n04xObQw2MxvWxPS82v6vO8bDmgw0WkQWjZ+H6EGCcj6n1nF654hu7ZjOwbTEI7UPR3SRWDWpPxsUxeuxO7UpQ50MmAokkOEe2nhX9bt7wDDmkvKP6MjUNMgRvu1Y8QJW2+2nevD6eK1+DFLEgALTjZlQDa8wde3MHL3f+QDDittwJgYjyKa+6YeTrNrmnGRCk7y9sn6PjY1zutsgzovuJ3EqY2p+Qhqurvcqr67KGSNegOtOFci18E3JgUCTAzdxKfLK0P9sDA2vp9Rg/IOW5glVZzUqisuHWyKODn1JFLkyEKUQbn1tDECJlwtSNMarQ0f9wECqg+mcm+sbEQDpR5A7dmp1X766mNy5sUrnJ48tH1ZODDsSj2rYfblCVbIoRUREoXatacHrSRMjvdFCtwQFvfLVRdal1vHrbfrVFyvbKT4/r/yq4vW4FKRuojbFh6I0/AkN7BHprrVl6f+8MofkaeiXpEuP18Zek4GRzo9FyvtFYBft4nRdYABj64HzvS1lX0I5V1ZBD1NF8QuqFx3BHpaw23q/SLrW1+Bthexrw==,iv:ITNaPjkiHMsQvEXvpR46pnySaxGDDQybVLws2fSXK/Q=,tag:z9TPRRUc5M3eUawAYYOy6g==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1q8332uuxust6e558xj3c535xtrq3ms0v3hdwqdf27ncjukgy0g9sdpd8hh",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya2t4bW4yNjVSYTg1Smpk\nYzdxemxKZEk0QkYveWpnZEIzamhFV3k2WjJNCldNMDdBSFVUZ3ZTNzlQSXNjV0h3\neVU3eThhWWttMjZabjVQT0pRbW5hNmsKLS0tIFlzVW1GTmNMdSthbmhzOG1neWxP\nMDdscnNUSDZIWG5TUVVHaFVEeG04WFkKf+iyZSzZvrO6DG23Y1WgLUPvM2EYUIa0\nNGO+s/QTCSYGcDOZLYSPfDPm5JxKdyt7w7jqHQGGjhrGDGY4ubzm2A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-06-28T23:19:03Z",
		"mac": "ENC[AES256_GCM,data:JSJRk7qalWPtde1DgCAABuM8UsUxq/h4LsPIbEM2XYHo/6AHkxVqP3Eyamf2UqJI8W6EvFJvB7xdo8Mu45vAYJ9G6fSzmpU/+pcHb9GgmisVwLkwJo6p/Ju9bBx7pLka71feDvZmUPHHKtkKV9H/nNru0c1ndc9gdBWbew/DUEk=,iv:nKVkJA6uEhPkh6SRXZfqC382GU8pTcOye9Xb4yjx3OY=,tag:ac4NMjABsyEdI95wM3U6zQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
